import { IOrder } from "@/types/order-type";

export const mockOrders: IOrder[] = [
  {
    _id: "8237Tw15036",
    orderNumber: 15036,
    seller: "seller_001",
    buyer: {
      _id: "buyer_001",
      name: "Alice Johnson",
      email: "alice@example.com",
    },
    products: [
      {
        _id: "prod_001",
        seller: "seller_001",
        title: "Netting Mykonos Tunic Dress",
        description: "A lightweight summer dress perfect for beachwear.",
        price: 1250,
        salePrice: 999,
        warranty: "6 months",
        colors: ["Blue", "White"],
        stock: 20,
        images: ["/images/products/summer-dress.png"],
        tags: ["dress", "summer", "fashion"],
        features: ["Breathable fabric", "Machine washable"],
        category: "Clothing",
        brand: "By Milly Thornton",
        shippingCost: 20,
        ratings: [
          { user: "user_001", rating: 5 },
          { user: "user_002", rating: 4 },
        ],
        rating: 4.5,
        createdAt: "2025-01-01T10:00:00.000Z",
        updatedAt: "2025-01-10T12:00:00.000Z",
        quantity: 1,
      },
      {
        _id: "prod_002",
        seller: "seller_001",
        title: "Embroidered Sequin Mini Dress",
        description: "Elegant sequin dress for evening parties.",
        price: 1960,
        stock: 15,
        images: ["/images/products/evening-dress.png"],
        tags: ["dress", "party", "sequin"],
        category: "Clothing",
        brand: "By Sonia Agrover",
        createdAt: "2025-01-05T11:00:00.000Z",
        updatedAt: "2025-01-12T15:00:00.000Z",
        quantity: 1,
      },
    ],
    totalItems: 2,
    total: 3210,
    status: "processing",
    shippingAddress: "123 Fashion Street, New York, USA",
    date: "2018-01-17T10:00:00.000Z",
    timeline: [
      {
        status: "processing",
        timestamp: "2018-01-17T10:00:00.000Z",
        note: "Order placed successfully",
        updatedBy: {
          _id: "seller_001",
          name: "Seller Admin",
        },
      },
    ],
  },
  {
    _id: "7429Bx12847",
    orderNumber: 12847,
    seller: "seller_002",
    buyer: {
      _id: "buyer_002",
      name: "Bob Smith",
      email: "bob@example.com",
    },
    products: [
      {
        _id: "prod_003",
        seller: "seller_002",
        title: "Apple iPhone 14 128GB",
        description: "Latest iPhone 14 with 128GB storage.",
        price: 579000,
        stock: 50,
        images: ["/images/products/iphone-14.png"],
        tags: ["phone", "apple", "electronics"],
        category: "Electronics",
        brand: "Apple",
        createdAt: "2025-01-02T09:00:00.000Z",
        updatedAt: "2025-01-11T10:00:00.000Z",
        quantity: 1,
      },
    ],
    totalItems: 1,
    total: 579000,
    status: "delivered",
    shippingAddress: "456 Tech Avenue, San Francisco, USA",
    date: "2018-01-14T09:00:00.000Z",
    timeline: [
      {
        status: "processing",
        timestamp: "2018-01-14T09:00:00.000Z",
        note: "Order placed successfully",
        updatedBy: {
          _id: "seller_002",
          name: "Seller Admin",
        },
      },
      {
        status: "delivered",
        timestamp: "2018-01-20T14:00:00.000Z",
        note: "Order delivered",
        updatedBy: {
          _id: "seller_002",
          name: "Seller Admin",
        },
      },
    ],
  },
  {
    _id: "5621Mx98234",
    orderNumber: 98234,
    seller: "seller_003",
    buyer: {
      _id: "buyer_003",
      name: "Charlie Brown",
      email: "charlie@example.com",
    },
    products: [
      {
        _id: "prod_004",
        seller: "seller_003",
        title: "Nike Air Max Sneakers",
        description: "Comfortable sneakers for everyday wear.",
        price: 150,
        stock: 100,
        images: ["/images/products/white-casual-sneakers.png"],
        tags: ["sneakers", "nike", "shoes"],
        category: "Footwear",
        brand: "Nike",
        createdAt: "2025-01-03T08:00:00.000Z",
        updatedAt: "2025-01-13T09:00:00.000Z",
        quantity: 2,
      },
    ],
    totalItems: 2,
    total: 300,
    status: "processing",
    shippingAddress: "789 Sports Lane, Chicago, USA",
    date: "2018-01-11T08:30:00.000Z",
    timeline: [
      {
        status: "processing",
        timestamp: "2018-01-11T08:30:00.000Z",
        note: "Order placed successfully",
        updatedBy: {
          _id: "seller_003",
          name: "Seller Admin",
        },
      },
    ],
  },
];
